version: '2'
services:
  #scale this with docker-compose scale es=3
  #elasticsearch configuration node, should not be scaled
  #config is under /usr/share/elasticsearch/config
  #data is under /usr/share/elasticsearch/data
  #to change the value of vm.max_map_count, you can add the following env:
  #ulimits:
  #  nofile:
  #    soft: 65536
  #    hard: 65536
  elasticsearch:
    image: elasticsearch:5.4
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9300"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/data/elasticsearch:/usr/share/elasticsearch/data
      - /opt/es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
