# This compose file will boot a elk cluster.
#   elasticsearch will listen on local 9200, and  use /opt/data/elasticsearch for storage.
#   es node can scale out.
#   kibana will liten on local 5601.
# https://github.com/yeasy/docker-compose-files


version: '2'
services:
  # scale this with docker-compose scale es=3
  #elasticsearch configuration node, should not be scaled
  #config is under /usr/share/elasticsearch/config
  #data is under /usr/share/elasticsearch/data
  elasticsearch:
    image: elasticsearch:5.4
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
      - "8080:8080"  # for logoxy
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/data/elasticsearch:/usr/share/elasticsearch/data
      - /opt/es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:5.4
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    environment:
      - TZ=Asia/Shanghai

  logstash:
    image: logstash:latest
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    links:
      - elasticsearch:elasticsearch
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/logstash/logstash.conf:/etc/logstash.conf
    command: logstash -f /etc/logstash.conf

  logoxy:
    image: yeasy/logoxy:latest
    network_mode: "service:elasticsearch"
    environment:
      - TZ=Asia/Shanghai
      - LOGOXY_ES_SERVER=localhost:9200
